apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bacteria-monitor
spec:
  selector:
    matchLabels:
      app: bacteria-stable
  endpoints:
    - port: metrics
      path: /metrics
